# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.2
_src_path: gh:quickplates/meta
accountname: quickplates
description: Litestar app template 🌠
example: true
exampleaccountname: quickplates
exampledescription: Litestar app example 🌠
examplereponame: litestar-example
reponame: litestar
repourl: https://github.com/quickplates/litestar
type: app
